openapi: '3.0.0'
info:
  title: Expenses api
  description: 'My first swagger'
tags:
  - name: user
    description: User data
  - name: financial-transaction
    description: Data related to financial-transaction entries
  - name: savingsGoal
    description: Data related to saving goals entries
  - name: category
    description: Data related to categories
paths:
  /user:
    get:
      description: Returns current user
      tags:
        - user
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  # user management apis that are not to be implemeneted unless I will create some admin view
  # /users:
  #   get:
  #     description: Returns users
  #     tags:
  #       - user
  #     responses:
  #       '200':
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/user'
  # /user/id:
  #   get:
  #     description: Returns given user
  #     tags:
  #       - user
  #     parameters:
  #       id:
  #         type: string
  #     responses:
  #       '200':
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/user'

  /financial-transaction/id:
    get:
      tags:
        - financial-transaction
      description: show financial-transaction by id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financial-transaction'
    put:
      tags:
        - financial-transaction
      description: update financial-transaction by id
      parameters:
        - in: path
          name: value
          schema:
            type: number
        - in: path
          name: subcategoryId
          schema:
            type: number
        - in: path
          name: description
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financial-transaction'
  /financial-transactions:
    get:
      tags:
        - financial-transaction
      description: show all financial-transactions for current user
      parameters:
        id:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/financial-transaction'
  /financial-transaction:
    post:
      tags:
        - financial-transaction
      description: add new financial-transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                value:
                  type: number
                subcategoryId:
                  type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financial-transaction'

  /savings-goal/id:
    get:
      tags:
        - savingsGoal
      description: show financial-transaction by id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/savingsGoal'
    put:
      tags:
        - savingsGoal
      description: update financial-transaction by id
      parameters:
        - in: path
          name: value
          schema:
            type: number
        - in: path
          name: totalValue
          schema:
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/savingsGoal'

  /savings-goals:
    get:
      tags:
        - savingsGoal
      description: get all savings goals for current user
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/savingsGoal'
  /savings-goal:
    post:
      tags:
        - savingsGoal
      description: add new savings goal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                totalValue:
                  type: number
                currentValue:
                  type: number
        name:
          type: string
        totalValue:
          type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/savingsGoal'

  /category/id:
    get:
      tags:
        - category
      description: show category by id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
    put:
      tags:
        - category
      description: update category by id
      parameters:
        - in: path
          name: name
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
  /categories:
    get:
      tags:
        - category
      description: show all categories for current user
      parameters:
        id:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/category'
  /subcategory/id:
    get:
      tags:
        - category
      description: show subcategory by id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subcategory'
    put:
      tags:
        - category
      description: update subcategory by id
      parameters:
        - in: path
          name: name
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
  /subcategories/id:
    get:
      tags:
        - category
      description: show all subcategories categories for given category
      parameters:
        id:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/subcategory'

components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        currentBalance:
          type: number
    financial-transaction:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
        subcategoryId:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        type:
          type: string
          enum:
            $ref: '#/components/schemas/financial-transaction-type'
    financial-transaction-type:
      type: string
      enum:
        - expense
        - gain
        - saving
    savingsGoal:
      type: object
      properties:
        id:
          type: string
        totalValue:
          type: number
        currentValue:
          type: number
        name:
          type: string
    recurringActions:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - financial-transaction
            - gain
            - saving
        savingId:
          type: string
          description: Only required for saving type
        value:
          type: number
    category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        subcategories:
          type: array
          items:
            $ref: '#/components/schemas/subcategory'
    subcategory:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        categoryId:
          type: string
