openapi: '3.0.0'
info:
  title: Expenses api
  description: 'My first swagger'
tags:
  - name: user
    description: User data
  - name: expense
    description: Data related to expense entries
  - name: savingsGoal
    description: Data related to saving goals entries
paths:
  /user:
    get:
      description: Returns current user
      tags:
        - user
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
  # user management apis that are not to be implemeneted unless I will create some admin view
  # /users:
  #   get:
  #     description: Returns users
  #     tags:
  #       - user
  #     responses:
  #       '200':
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/user'
  # /user/id:
  #   get:
  #     description: Returns given user
  #     tags:
  #       - user
  #     parameters:
  #       id:
  #         type: string
  #     responses:
  #       '200':
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/user'

  /expense/id:
    get:
      tags:
        - expense
      description: show expense by id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/expense'
    put:
      tags:
        - expense
      description: update expense by id
      parameters:
        - in: path
          name: value
          schema:
            type: number
        - in: path
          name: subcategoryId
          schema:
            type: number
        - in: path
          name: description
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/expense'
  /expenses:
    get:
      tags:
        - expense
      description: show all expenses for current user
      parameters:
        id:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/expense'
  /expense:
    post:
      tags:
        - expense
      description: add new expense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                value:
                  type: number
                subcategoryId:
                  type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/expense'

  /savings-goal/id:
    get:
      tags:
        - savingsGoal
      description: show expense by id
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/savingsGoal'
    put:
      tags:
        - savingsGoal
      description: update expense by id
      parameters:
        - in: path
          name: value
          schema:
            type: number
        - in: path
          name: totalValue
          schema:
            type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/savingsGoal'

  /savings-goals:
    get:
      tags:
        - savingsGoal
      description: get all savings goals for current user
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/savingsGoal'
  /savings-goal:
    post:
      tags:
        - savingsGoal
      description: add new savings goal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                totalValue:
                  type: number
                currentValue:
                  type: number
        name:
          type: string
        totalValue:
          type: number
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/savingsGoal'

components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        currentBalance:
          type: number
    expense:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
        subcategoryId:
          type: string
        date:
          type: string
        description:
          type: string
    savingsGoal:
      type: object
      properties:
        id:
          type: string
        totalValue:
          type: number
        currentValue:
          type: number
        name:
          type: string
    recurringActions:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - expense
            - gain
            - saving
        savingId:
          type: string
          description: Only required for saving type
        value:
          type: number
    category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    subcategory:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        categoryId:
          type: string
